String SendHTML(){
  float temperatura = 1.17;
  String page="";
page+="\n<!DOCTYPE html>";
page+="\n<html lang=\"es\">";
page+="\n  <head>";
page+="\n    <meta charset=\"UTF-8\" />";
page+="\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />";
page+="\n    <title>Fotobiomodulación</title>";
page+="\n    <style>";
page+="\n      body {";
page+="\n        font-family: Arial, sans-serif;";
page+="\n        background-color: #f4f4f9;";
page+="\n        color: #333;";
page+="\n        margin: 0;";
page+="\n        padding: 0;";
page+="\n      }";
page+="\n";
page+="\n      h1 {";
page+="\n        text-align: center;";
page+="\n        margin-top: 20px;";
page+="\n      }";
page+="\n";
page+="\n      #led-control {";
page+="\n        display: flex;";
page+="\n        flex-direction: column;";
page+="\n        align-items: center;";
page+="\n        margin: 20px;";
page+="\n      }";
page+="\n";
page+="\n      #controls,";
page+="\n      #password-container,";
page+="\n      #slider-controls,";
page+="\n      #sensor-data,";
page+="\n      #info-pain-relief,";
page+="\n      #info-tissue-treatment,";
page+="\n      #info-hair-growth,";
page+="\n      #table-container {";
page+="\n        margin: 20px 0;";
page+="\n      }";
page+="\n";
page+="\n      #controls button,";
page+="\n      #password-container button,";
page+="\n      #show-table-button,";
page+="\n      #table-container button {";
page+="\n        padding: 10px 20px;";
page+="\n        margin: 5px;";
page+="\n        border: none;";
page+="\n        background-color: #007bff;";
page+="\n        color: white;";
page+="\n        cursor: pointer;";
page+="\n        border-radius: 5px;";
page+="\n      }";
page+="\n";
page+="\n      #controls button:hover,";
page+="\n      #password-container button:hover,";
page+="\n      #show-table-button:hover,";
page+="\n      #table-container button:hover {";
page+="\n        background-color: #0056b3;";
page+="\n      }";
page+="\n";
page+="\n      #password-input {";
page+="\n        padding: 10px;";
page+="\n        margin-right: 5px;";
page+="\n        border-radius: 5px;";
page+="\n        border: 1px solid #ccc;";
page+="\n      }";
page+="\n";
page+="\n      #manual-control {";
page+="\n        display: flex;";
page+="\n        flex-direction: column;";
page+="\n        align-items: center;";
page+="\n        width: 100%;";
page+="\n      }";
page+="\n";
page+="\n      #slider-controls {";
page+="\n        display: flex;";
page+="\n        flex-direction: column;";
page+="\n        align-items: center;";
page+="\n        width: 100%;";
page+="\n      }";
page+="\n";
page+="\n      .slider-container {";
page+="\n        margin: 10px 0;";
page+="\n        width: 80%;";
page+="\n      }";
page+="\n";
page+="\n      .slider-label {";
page+="\n        display: block;";
page+="\n        margin-bottom: 5px;";
page+="\n        text-align: center;";
page+="\n      }";
page+="\n";
page+="\n      .slider {";
page+="\n        width: 100%;";
page+="\n      }";
page+="\n";
page+="\n      #timer-container,";
page+="\n      #message {";
page+="\n        text-align: center;";
page+="\n        margin: 20px;";
page+="\n      }";
page+="\n";
page+="\n      #cancel {";
page+="\n        background-color: #dc3545;";
page+="\n        color: white;";
page+="\n        padding: 10px 20px;";
page+="\n        border: none;";
page+="\n        cursor: pointer;";
page+="\n        border-radius: 5px;";
page+="\n      }";
page+="\n";
page+="\n      #cancel:hover {";
page+="\n        background-color: #c82333;";
page+="\n      }";
page+="\n";
page+="\n      #sensor-data {";
page+="\n        text-align: center;";
page+="\n        margin: 20px;";
page+="\n      }";
page+="\n";
page+="\n      #sensor-data div {";
page+="\n        margin: 10px 0;";
page+="\n      }";
page+="\n";
page+="\n      .calor {";
page+="\n        color: red;";
page+="\n      }";
page+="\n";
page+="\n      .frio {";
page+="\n        color: blue;";
page+="\n      }";
page+="\n";
page+="\n      #info-control {";
page+="\n        display: flex;";
page+="\n        flex-direction: column;";
page+="\n        align-items: center;";
page+="\n        margin: 20px;";
page+="\n      }";
page+="\n";
page+="\n      #info-control div {";
page+="\n        margin: 10px 0;";
page+="\n        text-align: center;";
page+="\n      }";
page+="\n";
page+="\n      #table-container {";
page+="\n        display: none;";
page+="\n        width: 80%;";
page+="\n        margin: 0 auto;";
page+="\n      }";
page+="\n";
page+="\n      #records-table {";
page+="\n        width: 100%;";
page+="\n        border-collapse: collapse;";
page+="\n      }";
page+="\n";
page+="\n      #records-table th,";
page+="\n      #records-table td {";
page+="\n        padding: 10px;";
page+="\n        text-align: center;";
page+="\n        border: 1px solid #ccc;";
page+="\n      }";
page+="\n";
page+="\n      #records-table th {";
page+="\n        background-color: #007bff;";
page+="\n        color: white;";
page+="\n      }";
page+="\n";
page+="\n      #records-table tbody tr:nth-child(even) {";
page+="\n        background-color: #f4f4f9;";
page+="\n      }";
page+="\n";
page+="\n      #records-table tbody tr:nth-child(odd) {";
page+="\n        background-color: #fff;";
page+="\n      }";
page+="\n    </style>";
page+="\n  </head>";
page+="\n  <body>";
page+="\n    <h1>Sistemas Embebidos - Fotobiomodulación</h1>";
page+="\n    <div id=\"led-control\">";
page+="\n      <h2>Bienvenido</h2>";
page+="\n      <h3 id=\"paragraph\">";
page+="\n        Selecciona cualquiera de las opciones para comenzar con la sesión";
page+="\n      </h3>";
page+="\n      <div id=\"controls\">";
page+="\n        <button id=\"btn1\" onclick=\"sendData('button1')\">Botón 1</button>";
page+="\n        <button id=\"btn2\" onclick=\"sendData('button2')\">Botón 2</button>";
page+="\n        <button id=\"btn3\" onclick=\"sendData('button3')\">Botón 3</button>";
page+="\n        <button id=\"btn4\" onclick=\"sendData('button4')\">Botón 4</button>";
page+="\n        <button id=\"btn5\" onclick=\"sendData('button5')\">Botón 5</button>";
page+="\n      </div>";
page+="\n      <div id=\"password-container\">";
page+="\n        <input";
page+="\n          type=\"password\"";
page+="\n          id=\"password-input\"";
page+="\n          placeholder=\"Introduce la contraseña\"";
page+="\n        />";
page+="\n        <button id=\"password-button\" onclick=\"checkPassword()\">";
page+="\n          Control Manual";
page+="\n        </button>";
page+="\n      </div>";
page+="\n      <div id=\"manual-control\" style=\"display: none;\">";
page+="\n        <div id=\"slider-controls\">";
page+="\n          <div class=\"slider-container\">";
page+="\n            <label for=\"slider1\" class=\"slider-label\">Intensidad</label>";
page+="\n            <input";
page+="\n              type=\"range\"";
page+="\n              id=\"slider1\"";
page+="\n              class=\"slider\"";
page+="\n              min=\"0\"";
page+="\n              max=\"100\"";
page+="\n              value=\"50\"";
page+="\n              oninput=\"sendSliderData()\"";
page+="\n            />";
page+="\n          </div>";
page+="\n          <div class=\"slider-container\">";
page+="\n            <label for=\"slider2\" class=\"slider-label\">Duración</label>";
page+="\n            <input";
page+="\n              type=\"range\"";
page+="\n              id=\"slider2\"";
page+="\n              class=\"slider\"";
page+="\n              min=\"0\"";
page+="\n              max=\"60\"";
page+="\n              value=\"30\"";
page+="\n              oninput=\"sendSliderData()\"";
page+="\n            />";
page+="\n          </div>";
page+="\n          <div class=\"slider-container\">";
page+="\n            <label for=\"slider3\" class=\"slider-label\">Frecuencia</label>";
page+="\n            <input";
page+="\n              type=\"range\"";
page+="\n              id=\"slider3\"";
page+="\n              class=\"slider\"";
page+="\n              min=\"1\"";
page+="\n              max=\"10\"";
page+="\n              value=\"5\"";
page+="\n              oninput=\"sendSliderData()\"";
page+="\n            />";
page+="\n          </div>";
page+="\n        </div>";
page+="\n        <button id=\"show-table-button\" onclick=\"showTable()\">Mostrar Registros</button>";
page+="\n      </div>";
page+="\n      <div id=\"timer-container\">";
page+="\n        <div><strong>Tiempo restante de la sesión</strong></div>";
page+="\n        <div id=\"timer\"></div>";
page+="\n      </div>";
page+="\n      <button";
page+="\n        id=\"cancel\"";
page+="\n        onclick=\"cancelTimer()\"";
page+="\n        style=\"";
page+="\n          background-color: #dc3545;";
page+="\n          display: none;";
page+="\n          margin: 0 auto;";
page+="\n          align-self: center;";
page+="\n        \"";
page+="\n      >";
page+="\n        Terminar con la sesión";
page+="\n      </button>";
page+="\n      <div id=\"message\">La sesión ha terminado</div>";
page+="\n    </div>";
page+="\n    <div id=\"info-control\">";
page+="\n      <div id=\"sensor-data\">";
page+="\n        <div>";
page+="\n          <strong>Temperatura: </strong";
page+="\n          ><span id=\"valor-temperatura\">-- °C</span>";
page+="\n        </div>";
page+="\n        <div>";
page+="\n          <strong>Oxigenación: </strong";
page+="\n          ><span id=\"valor-oxigenacion\">-- %</span>";
page+="\n        </div>";
page+="\n        <div>";
page+="\n          <strong>Ritmo Cardíaco: </strong";
page+="\n          ><span id=\"valor-ritmo-cardiaco\">-- bpm</span>";
page+="\n        </div>";
page+="\n      </div>";
page+="\n    </div>";
page+="\n";
page+="\n    <div id=\"table-container\" style=\"display: none;\">";
page+="\n      <h2>Registros</h2>";
page+="\n      <table id=\"records-table\">";
page+="\n        <thead>";
page+="\n          <tr>";
page+="\n            <th>ID</th>";
page+="\n            <th>Fecha</th>";
page+="\n            <th>Valor 1</th>";
page+="\n            <th>Valor 2</th>";
page+="\n            <th>Valor 3</th>";
page+="\n          </tr>";
page+="\n        </thead>";
page+="\n        <tbody>";
page+="\n          <!-- Filas de datos se insertarán aquí -->";
page+="\n        </tbody>";
page+="\n      </table>";
page+="\n      <button onclick=\"hideTable()\">Volver</button>";
page+="\n    </div>";
page+="\n";
page+="\n    <script>";
page+="\n      const correctPassword = \"12345\"; // Contraseña correcta";
page+="\n      const esp32Ip = \"http://192.168.1.1\"; ";
page+="\n";
page+="\n      function checkPassword() {";
page+="\n        const inputPassword = document.getElementById(\"password-input\").value;";
page+="\n        if (inputPassword === correctPassword) {";
page+="\n          document.getElementById(\"manual-control\").style.display = \"flex\";";
page+="\n        } else {";
page+="\n          alert(\"Contraseña incorrecta\");";
page+="\n        }";
page+="\n      }";
page+="\n";
page+="\n      function sendData(button) {";
page+="\n        fetch(`${esp32Ip}/${button}`, {";
page+="\n          method: \"GET\",";
page+="\n        })";
page+="\n          .then((response) => response.text())";
page+="\n          .then((data) => console.log(data))";
page+="\n          .catch((error) => console.error(\"Error:\", error));";
page+="\n      }";
page+="\n";
page+="\n      function sendSliderData() {";
page+="\n        const intensity = document.getElementById(\"slider1\").value;";
page+="\n        const duration = document.getElementById(\"slider2\").value;";
page+="\n        const frequency = document.getElementById(\"slider3\").value;";
page+="\n";
page+="\n        const url = `${esp32Ip}/slider?intensity=${intensity}&duration=${duration}&frequency=${frequency}`;";
page+="\n";
page+="\n        fetch(url, {";
page+="\n          method: \"GET\",";
page+="\n        })";
page+="\n          .then((response) => response.text())";
page+="\n          .then((data) => console.log(data))";
page+="\n          .catch((error) => console.error(\"Error:\", error));";
page+="\n      }";
page+="\n";
page+="\n      let timer;";
page+="\n      let countdown;";
page+="\n";
page+="\n      function confirmStart(duration, infoId) {";
page+="\n        if (confirm(\"¿Deseas iniciar la sesión?\")) {";
page+="\n          startTimer(duration);";
page+="\n          document.getElementById(infoId).style.display = \"block\";";
page+="\n          document.getElementById(\"cancel\").style.display = \"block\";";
page+="\n          document.getElementById(\"message\").style.display = \"none\";";
page+="\n        }";
page+="\n      }";
page+="\n";
page+="\n      function startTimer(duration) {";
page+="\n        let timerDisplay = document.getElementById(\"timer\");";
page+="\n        let time = duration * 60;";
page+="\n        clearInterval(countdown);";
page+="\n        document.getElementById(\"timer-container\").style.display = \"block\";";
page+="\n        countdown = setInterval(() => {";
page+="\n          let minutes = Math.floor(time / 60);";
page+="\n          let seconds = time % 60;";
page+="\n          timerDisplay.innerHTML =";
page+="\n            (minutes < 10 ? \"0\" : \"\") +";
page+="\n            minutes +";
page+="\n            \":\" +";
page+="\n            (seconds < 10 ? \"0\" : \"\") +";
page+="\n            seconds;";
page+="\n          time--;";
page+="\n          if (time < 0) {";
page+="\n            clearInterval(countdown);";
page+="\n            document.getElementById(\"message\").style.display = \"block\";";
page+="\n            document.getElementById(\"timer-container\").style.display = \"none\";";
page+="\n            document.getElementById(\"cancel\").style.display = \"none\";";
page+="\n          }";
page+="\n        }, 1000);";
page+="\n      }";
page+="\n";
page+="\n      function cancelTimer() {";
page+="\n        clearInterval(countdown);";
page+="\n        document.getElementById(\"timer-container\").style.display = \"none\";";
page+="\n        document.getElementById(\"cancel\").style.display = \"none\";";
page+="\n        document.getElementById(\"message\").style.display = \"none\";";
page+="\n      }";
page+="\n";
page+="\n      function updateSensors() {";
page+="\n        const tempElement = document.getElementById(\"valor-temperatura\");";
page+="\n        const oxigenacionElement = document.getElementById(\"valor-oxigenacion\");";
page+="\n        const ritmoElement = document.getElementById(\"valor-ritmo-cardiaco\");";
page+="\n";
page+="\n        console.log(\"updating\");";
page+="\n        const url = `${esp32Ip}/update`;";
page+="\n        fetch(url, {";
page+="\n          method: \"GET\",";
page+="\n        })";
page+="\n        .then((response) => response.json()) // Parse the JSON string in the response";
page+="\n        .then((data) => {";
page+="\n          console.log(data); // Handle the parsed data";
page+="\n";
page+="\n          const temperatura = data.temperatura;";
page+="\n          const oxigenacion = data.oxigenacion;";
page+="\n          const ritmo = data.pulso;";
page+="\n";
page+="\n          tempElement.textContent = `${temperatura.toFixed(1)} °C`;";
page+="\n          oxigenacionElement.textContent = `${oxigenacion.toFixed(1)} %`;";
page+="\n          ritmoElement.textContent = `${ritmo.toFixed(0)} bpm`;";
page+="\n";
page+="\n          if (temperatura >= 38) {";
page+="\n            tempElement.classList.add(\"calor\");";
page+="\n            tempElement.classList.remove(\"frio\");";
page+="\n          } else if (temperatura <= 36) {";
page+="\n            tempElement.classList.add(\"frio\");";
page+="\n            tempElement.classList.remove(\"calor\");";
page+="\n          } else {";
page+="\n            tempElement.classList.remove(\"calor\", \"frio\");";
page+="\n          }";
page+="\n";
page+="\n        })";
page+="\n        .catch((error) => console.error(\"Error:\", error));";
page+="\n      }";
page+="\n";
page+="\n      setInterval(updateSensors, 1000);";
page+="\n";
page+="\n      function showTable() {";
page+="\n        document.getElementById(\"led-control\").style.display = \"none\";";
page+="\n        document.getElementById(\"info-control\").style.display = \"none\";";
page+="\n        document.getElementById(\"table-container\").style.display = \"block\";";
page+="\n";
page+="\n        fetchRecords();";
page+="\n      }";
page+="\n";
page+="\n      function hideTable() {";
page+="\n        document.getElementById(\"table-container\").style.display = \"none\";";
page+="\n        document.getElementById(\"led-control\").style.display = \"block\";";
page+="\n        document.getElementById(\"info-control\").style.display = \"block\";";
page+="\n      }";
page+="\n";
page+="\n      function fetchRecords() {";
page+="\n        // Reemplaza la URL con la de tu servidor que devuelve los registros";
page+="\n        const url = \"http://192.168.1.2/\";";
page+="\n";
page+="\n        fetch(url)";
page+="\n          .then((response) => response.json())";
page+="\n          .then((data) => {";
page+="\n            const tableBody = document.getElementById(\"records-table\").querySelector(\"tbody\");";
page+="\n            tableBody.innerHTML = \"\"; // Limpiar la tabla";
page+="\n";
page+="\n            data.forEach((record) => {";
page+="\n              const row = document.createElement(\"tr\");";
page+="\n              row.innerHTML = `";
page+="\n                <td>${record.id}</td>";
page+="\n                <td>${record.date}</td>";
page+="\n                <td>${record.value1}</td>";
page+="\n                <td>${record.value2}</td>";
page+="\n                <td>${record.value3}</td>";
page+="\n              `;";
page+="\n              tableBody.appendChild(row);";
page+="\n            });";
page+="\n          })";
page+="\n          .catch((error) => console.error(\"Error fetching records:\", error));";
page+="\n      }";
page+="\n    </script>";
page+="\n  </body>";
page+="\n</html>";

  return page;
}